# Generated by Django 2.2.3 on 2020-07-31 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('opt1', models.CharField(max_length=50)),
                ('opt2', models.CharField(max_length=50)),
                ('opt3', models.CharField(max_length=50)),
                ('opt4', models.CharField(max_length=50)),
                ('opt5', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quiz_url', models.URLField(blank=True, null=True, unique=True)),
                ('answer', models.CharField(blank=True, default='', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('result', models.IntegerField(blank=True, default=0, null=True)),
                ('user_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.User')),
            ],
            options={
                'ordering': ['-result', 'name'],
            },
        ),
    ]
