# Generated by Django 2.2.3 on 2020-07-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenger',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
