# Generated by Django 2.2.3 on 2020-07-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_challenger_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quiz_title',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
